local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/imhenne187/SilenceElerium/refs/heads/main/src/SilenceEleriumLibrary.luau", true))()

local window = library:AddWindow("PURIFY", {
	title_bar = {
		Color3.fromRGB(34, 85, 34),   -- Forest Green
		Color3.fromRGB(22, 60, 22),   -- Deep Moss
		Color3.fromRGB(10, 30, 10)    -- Dark Pine
	},
	title_bar_transparency = 0.15,
	background = {
		Color3.fromRGB(8, 18, 8),     -- Dark Nature Base
		Color3.fromRGB(20, 40, 20),   -- Moss Green
		Color3.fromRGB(35, 55, 35)    -- Soft Forest
	},
	background_transparency = 0.08,
	main_color = Color3.fromRGB(80, 200, 120), -- Nature Accent Green
	min_size = Vector2.new(400, 300),
	can_resize = true
})

local farmtab = window:AddTab("main")
local petstab = window:AddTab("pets")
local killingtab = window:AddTab("killimg")
local creditstab = window:AddTab("credentials")
creditstab:Show()

farmtab:AddButton("strength station",function()
	-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").RemotesEvent.MachineActiveFunction
Event:InvokeServer(
    workspace.MachinesFolder["Squat Ocean"],
    true
)
end)

local MachineEvent = game:GetService("ReplicatedStorage").RemotesEvent.MachineActiveEvent

farmtab:AddSwitch("auto rep", function(bool)
    getgenv().AutoRep = bool

    while getgenv().AutoRep do
        MachineEvent:FireServer()
        task.wait(0.01)
    end
end):Set(true)
